BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Emagazine] (
    [id] INT NOT NULL IDENTITY(1,1),
    [title] NVARCHAR(1000) NOT NULL,
    [thumbnail] VARCHAR(max),
    [url] VARCHAR(max),
    [month] NVARCHAR(1000) NOT NULL,
    [year] NVARCHAR(1000) NOT NULL,
    CONSTRAINT [Emagazine_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
