BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Test] (
    [id] NVARCHAR(1000) NOT NULL,
    [key] NVARCHAR(1000) NOT NULL,
    CONSTRAINT [Test_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- CreateTable
CREATE TABLE [dbo].[Advertisement] (
    [id] INT NOT NULL IDENTITY(1,1),
    [base64] NVARCHAR(1000),
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Advertisement_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [updatedAt] DATETIME2 NOT NULL,
    CONSTRAINT [Advertisement_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
